% Render every Claim of a theory as a Markdown table, in Core order.
%
%   swipl framework/tools/render_claims.pl <TheoryDir> > <TheoryDir>/rendering.md
%
% The table is the rendering of record for a pull request: regenerate it
% after every Core change and let CI compare it with the committed copy, so
% that the rendering a reviewer reads is the one render/2 gives, never one
% typed by hand. Status is listed so that a provisional Claim reads as one.

:- initialization(main, main).
:- prolog_load_context(directory, D), atom_concat(D, '/../prolog/framework', F), use_module(F).

main([Dir]) :-
    load_theory(Dir),
    format("<!-- Generated by framework/tools/render_claims.pl; regenerate, never edit. -->~n~n"),
    format("| Claim | Status | Rendering |~n|---|---|---|~n"),
    forall(framework:claim(Name, Status, Head, Body),
           ( clause_term(Head, Body, Term), render(Term, English),
             format("| `~w` | ~w | ~w |~n", [Name, Status, English]) )).
main(_) :- format(user_error, "usage: swipl framework/tools/render_claims.pl <TheoryDir>~n"), halt(1).

clause_term(Head, true, Head) :- !.
clause_term(Head, Body, (Head :- Body)).
